'\" t
.\"     Title: gnome-terminal
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: June 2020
.\"    Manual: User Commands
.\"    Source: GNOME
.\"  Language: English
.\"
.TH "GNOME\-TERMINAL" "1" "June 2020" "GNOME" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gnome-terminal \- A terminal emulator for GNOME
.SH "SYNOPSIS"
.HP \w'\fBgnome\-terminal\fR\ 'u
\fBgnome\-terminal\fR [\fIOPTION\fR...] [\-\- \fIPROGRAM\fR [\fIARG\fR...]]
.SH "DESCRIPTION"
.PP
\fBgnome\-terminal\fR
is a terminal emulator application for accessing a UNIX shell environment which can be used to run programs available on your system\&. It supports several profiles, multiple tabs and implements several keyboard shortcuts\&.
.SH "OPTIONS"
.PP
\fB\-\-help, \-h\fR
.RS 4
Show a brief overview of all the options\&.
.RE
.PP
\fB\-\-help\-all\fR
.RS 4
Show all the options in detail\&.
.RE
.PP
\fB\-\-help\-gtk\fR
.RS 4
Show all the GTK options\&.
.RE
.PP
\fB\-\-help\-terminal\fR
.RS 4
Show all the options to select between new terminal tabs or windows\&.
.RE
.PP
\fB\-\-help\-terminal\-options\fR
.RS 4
Show all the options to change the attributes of terminals regardless of whether they are in separate tabs or windows\&.
.RE
.PP
\fB\-\-help\-window\-options\fR
.RS 4
Show all the options to change the attributes of windows containing terminals\&.
.RE
.PP
\fB\-\-load\-config=FILE\fR
.RS 4
Restore the application to a previously saved state by loading it from a configuration file\&.
.RE
.PP
\fB\-\-preferences\fR
.RS 4
Show the preferences window\&.
.RE
.PP
\fB\-\-print\-environment, \-p\fR
.RS 4
Print the environment variables to interact with newly created terminals\&.
.RE
.PP
\fB\-\-quiet, \-q\fR
.RS 4
Suppress diagnostics\&.
.RE
.PP
\fB\-\-verbose, \-v\fR
.RS 4
Increase diagnostic verbosity\&.
.RE
.PP
\fB\-\-tab\fR
.RS 4
Open a new tab containing a terminal in the last\-opened window with the default profile\&.
.RE
.PP
\fB\-\-window\fR
.RS 4
Open a new window with a tab containing a terminal with the default profile\&.
.RE
.PP
\fB\-\-command, \-e=COMMAND\fR
.RS 4
Split the argument to this option into a program and arguments in the same way a shell would, and execute the resulting command\-line inside the terminal\&.
.sp
This option is deprecated\&. Instead, use
\fB\-\-\fR
to terminate the options, and put the program and arguments to execute after it: for example, instead of
\fBgnome\-terminal \-e "python3 \-q"\fR, prefer to use
\fBgnome\-terminal \-\- python3 \-q\fR\&.
.sp
Note that the
\fICOMMAND\fR
is not run via a shell: it is split into words and executed as a program\&. If shell syntax is required, use the form
\fBgnome\-terminal \-\- sh \-c \*(Aq\&.\&.\&.\*(Aq\fR\&.
.RE
.PP
\fB\-\-execute PROGRAM [ARGS], \-x PROGRAM [ARGS]\fR
.RS 4
Stop parsing options at this point, and interpret all subsequent options as a program and arguments to execute inside the terminal\&.
.sp
This option is deprecated: use
\fB\-\-\fR
instead\&. For example, instead of
\fBgnome\-terminal \-x python3 \-q\fR, prefer to use
\fBgnome\-terminal \-\- python3 \-q\fR\&.
.RE
.PP
\fB\-\-fd=FD\fR
.RS 4
Forward file descriptor\&.
.RE
.PP
\fB\-\-profile=PROFILE\-NAME\fR
.RS 4
Use the given profile instead of the default profile\&.
.RE
.PP
\fB\-\-title, \-t=TITLE\fR
.RS 4
Set the initial terminal title\&.
.RE
.PP
\fB\-\-wait\fR
.RS 4
Wait until the terminal\*(Aqs child exits\&.
.RE
.PP
\fB\-\-working\-directory=DIRNAME\fR
.RS 4
Set the terminal\*(Aqs working directory\&.
.RE
.PP
\fB\-\-zoom=ZOOM\fR
.RS 4
Set the terminal\*(Aqs zoom factor\&. 1\&.0 is normal size\&.
.RE
.PP
\fB\-\-active\fR
.RS 4
Set the last specified tab as the active one in its window\&.
.RE
.PP
\fB\-\-full\-screen\fR
.RS 4
Full\-screen the window\&.
.RE
.PP
\fB\-\-geometry=GEOMETRY\fR
.RS 4
Set the window size as COLSxROWS+X+Y\&. For example, 80x24 or 80x24+200+200\&.
.RE
.PP
\fB\-\-hide\-menubar\fR
.RS 4
Turn off the menubar for the window\&.
.RE
.PP
\fB\-\-show\-menubar\fR
.RS 4
Turn on the menubar for the window\&.
.RE
.PP
\fB\-\-maximize\fR
.RS 4
Maximize the window\&.
.RE
.PP
\fB\-\-role=ROLE\fR
.RS 4
Set the X window role\&.
.RE
.PP
\fB\-\-class=CLASS\fR
.RS 4
Program class as used by the window manager\&.
.RE
.PP
\fB\-\-display=DISPLAY\fR
.RS 4
X display to use\&.
.RE
.PP
\fB\-\-g\-fatal\-warnings\fR
.RS 4
Make all warnings fatal\&.
.RE
.PP
\fB\-\-gdk\-debug=FLAGS\fR
.RS 4
GDK debugging flags to set\&.
.RE
.PP
\fB\-\-gdk\-no\-debug=FLAGS\fR
.RS 4
GDK debugging flags to unset\&.
.RE
.PP
\fB\-\-gtk\-debug=FLAGS\fR
.RS 4
GTK debugging flags to set\&.
.RE
.PP
\fB\-\-gtk\-no\-debug=FLAGS\fR
.RS 4
GTK debugging flags to unset\&.
.RE
.PP
\fB\-\-gtk\-module=MODULES\fR
.RS 4
Load additional GTK modules\&.
.RE
.PP
\fB\-\-name=NAME\fR
.RS 4
Program name as used by the window manager\&.
.RE
.SH "BUGS"
.PP
Please read
\m[blue]\fB\%https://wiki.gnome.org/Apps/Terminal/ReportingBugs\fR\m[]
on how to report bugs\&.
.SH "EXAMPLES"
.PP
To run a terminal containing an interactive Python prompt:
.sp
.if n \{\
.RS 4
.\}
.nf
        gnome\-terminal \-\-title=Python \-\- python3 \-q
      
.fi
.if n \{\
.RE
.\}
.PP
To interpret shell syntax in a terminal, either write it in a separate shell script, or use
sh \-c:
.sp
.if n \{\
.RS 4
.\}
.nf
        gnome\-terminal \-\- sh \-c \*(Aqif [ "$(id \-u)" = 0 ]; then \&.\&.\&.\*(Aq
      
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.PP
For further information, visit the website
\m[blue]\fB\%https://wiki.gnome.org/Apps/Terminal\fR\m[]\&. There\*(Aqs a list of frequently asked questions at
\m[blue]\fB\%https://wiki.gnome.org/Apps/Terminal/FAQ\fR\m[]\&.
