
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef TERMINAL_TYPE_BUILTINS_H
#define TERMINAL_TYPE_BUILTINS_H

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "terminal-enums.h" */
GType terminal_new_terminal_mode_get_type (void);
#define TERMINAL_TYPE_NEW_TERMINAL_MODE (terminal_new_terminal_mode_get_type ())
GType terminal_new_tab_position_get_type (void);
#define TERMINAL_TYPE_NEW_TAB_POSITION (terminal_new_tab_position_get_type ())
GType terminal_exit_action_get_type (void);
#define TERMINAL_TYPE_EXIT_ACTION (terminal_exit_action_get_type ())
GType terminal_settings_list_flags_get_type (void);
#define TERMINAL_TYPE_SETTINGS_LIST_FLAGS (terminal_settings_list_flags_get_type ())
GType terminal_cjk_width_get_type (void);
#define TERMINAL_TYPE_CJK_WIDTH (terminal_cjk_width_get_type ())
GType terminal_theme_variant_get_type (void);
#define TERMINAL_TYPE_THEME_VARIANT (terminal_theme_variant_get_type ())
GType terminal_preserve_working_directory_get_type (void);
#define TERMINAL_TYPE_PRESERVE_WORKING_DIRECTORY (terminal_preserve_working_directory_get_type ())

G_END_DECLS

#endif /* !TERMINAL_TYPE_BUILTINS_H */

/* Generated data ends here */

